// ============================================================
// Supported Languages
// ============================================================

export type Language =
  | 'en'  // English
  | 'hi'  // Hindi
  | 'te'  // Telugu
  | 'ta'  // Tamil
  | 'bn'  // Bengali
  | 'mr'  // Marathi
  | 'gu'  // Gujarati
  | 'kn'  // Kannada
  | 'ml'  // Malayalam
  | 'pa'  // Punjabi
  | 'or'  // Odia
  | 'as'  // Assamese
  | 'ur'  // Urdu
  | 'sa'  // Sanskrit
  | 'mai' // Maithili
  | 'kok' // Konkani
  | 'ne'  // Nepali
  | 'sd'  // Sindhi
  | 'doi' // Dogri
  | 'brx' // Bodo
  | 'sat' // Santali
  | 'ks'  // Kashmiri
  | (string & {});

export type UserRole = 'artisan' | 'buyer';

export type CraftCategory =
  | 'Textiles & Handloom'
  | 'Clay & Terracotta'
  | 'Metalcraft & Dhokra'
  | 'Traditional Painting'
  | 'Woodcraft & Carving'
  | 'Leather & Footwear'
  | 'Handmade Jewelry'
  | 'Other Heritage Craft';

/**
 * Artisan verification tier.
 * 'normal'           → no badge (profile only)
 * 'identity_verified'→ 🟢 Government ID checked
 * 'gi_craft_verified'→ 🟣 GI/Artisan craft certificate checked
 *
 * These two verification types are intentionally kept separate.
 * Private documents are NEVER exposed publicly — only this tier flag is public.
 */
export type VerificationTier = 'normal' | 'identity_verified' | 'gi_craft_verified';

export interface ArtisanProfile {
  id: string;
  name: string;
  regionalName: string;
  phone: string;
  craftCluster: string;
  district: string;
  state: string;
  beneficiaryId: string; // MoSJE Beneficiary Card No
  shilpCardNumber: string;
  avatarUrl: string;
  giTagCraft: string;
  experienceYears: number;
  exhibitions: string[]; // e.g. ["Shilp Samagam 2024", "Dilli Haat", "Surajkund International Mela"]
  rating: number;
  totalSalesCount: number;
  totalEarnings: number;
  bankLinked: boolean;

  // ── New Supabase-backed fields ──────────────────────────────────────────────
  /** Unique ID generated by Shilp-AI: SHILP-{STATE}-{YEAR}-{5DIGIT} */
  shilpArtisanId?: string;
  /** Artisan verification tier — the only publicly visible verification indicator */
  verificationTier?: VerificationTier;
  /** Optional bio written during onboarding (may be AI-assisted but artisan-editable) */
  bio?: string;
  /** Whether the artisan has completed the onboarding wizard */
  onboardingComplete?: boolean;
  /** Supabase UUID (auth.users.id) — populated when the artisan is authenticated */
  supabaseUserId?: string;
}


export interface PricingBreakdown {
  rawMaterialCost: number;
  wastageBuffer: number; // 15%
  productionDays: number;
  dailyLaborRate: number; // ₹750/day fair artisan wage standard
  totalLaborWage: number;
  giComplexityMultiplier: number;
  artisanMarginPercent: number;
  artisanProfitAmount: number;
  suggestedRetailPrice: number; // MSRP
  fairMinimumPrice: number;
  marketBenchmarkMin: number;
  marketBenchmarkMax: number;
  recommendedPrice?: number;
  fairPriceRange?: {
    min: number;
    max: number;
  };
  modelType?: 'xgboost_regressor' | 'heuristic_ml';
  xgboostConfidence?: number;
  featureContributions?: {
    feature: string;
    impact: string;
    weight: number;
  }[];
  wholesaleTiers: {
    tier: string;
    minUnits: number;
    discountPercent: number;
    unitPrice: number;
  }[];
}

export interface ProductListing {
  id: string;
  artisanId: string;
  artisanName: string;
  state: string;

  titleEn: string;
  titleHi: string;

  category: CraftCategory;
  craftTechnique: string;
  primaryMaterial: string;
  color: string;

  productionDays: number;
  rawMaterialCost: number;

  originalImage: string;
  enhancedImage: string;
  originalImageUrl?: string;
  enhancedImageUrl?: string;

  hasBackgroundRemoved: boolean;
  hasLightingEnhanced: boolean;

  descriptionEn: string;
  descriptionHi: string;
  culturalContext?: string;
  seoKeywords: string[];
  searchTags?: string[];
  metaDescription?: string;
  pricing: PricingBreakdown;
  targetBuyers: string[];
  stockQuantity: number;
  giCertified: boolean;
  createdAt: string;

  featured?: boolean;

  productSize?: 'Small' | 'Medium' | 'Large' | 'Extra-Large';

  qualityTier?: 'Standard' | 'Premium Heritage' | 'Masterpiece';
  // Rich artisan-provided attributes — optional, backward-compatible with existing Firestore records
  productType?: string;       // e.g. "Shawl", "Saree", "Sculpture"
  style?: string;             // e.g. "Kashmiri", "Pochampally", "Banarasi"
  subject?: string;           // e.g. "Nandi", "Horse", "Tree of Life"
  weavingMethod?: string;     // e.g. "Handwoven", "Hand-spun"
  constructionMethod?: string;// e.g. "Hand-embroidered", "Block Printed"
  pattern?: string;           // e.g. "Floral", "Geometric"
  motif?: string;             // e.g. "Pink & Gold Floral"
  borderColor?: string;       // e.g. "Pink & Gold"
  dyeType?: string;           // e.g. "Natural Dye", "Vegetable Dye"
  zariType?: string;          // e.g. "100% Zari", "Gold Zari"
  fabricType?: string;        // e.g. "Mulberry Silk", "Pure Cotton"
  artisanClaims?: string[];   // explicitly stated claims: ["100% handmade", "natural dye"]
}

export interface CopilotMessage {
  id: string;
  sender: 'artisan' | 'copilot';
  text: string;
  audioText?: string;
  timestamp: string;

  actionCard?: {
    type:
      | 'product_extracted'
      | 'pricing_suggested'
      | 'listing_ready';
    data: any;
  };
}

export interface BulkRFQInquiry {
  id: string;
  buyerName: string;
  buyerCompany: string;
  buyerEmail: string;
  buyerPhone: string;
  productId: string;
  productTitle: string;
  requestedQuantity: number;
  offeredUnitPrice: number;
  deliveryDateNeeded: string;
  customizationNotes?: string;

  status:
    | 'pending'
    | 'accepted'
    | 'negotiating'
    | 'declined';

  createdAt: string;
}

// ============================================================
// NEW: Messaging, Customization Requests, Reviews
// ============================================================

export interface CustomizationRequest {
  color?: string;
  size?: string;
  material?: string;
  design?: string;
  quantity?: number;
  otherRequirements?: string;
  notes?: string;
}

export interface ChatMessage {
  id: string;
  conversationId: string;
  senderId: string;
  senderRole: UserRole;
  senderName: string;
  text: string;
  timestamp: string;

  customizationRequest?: CustomizationRequest;

  isRead: boolean;
  /** Optional image attachment URL (stored in Supabase chat-attachments bucket) */
  imageUrl?: string;
}

export interface Conversation {
  id: string;
  buyerId: string;
  buyerName: string;
  artisanId: string;
  artisanName: string;

  productId?: string;
  productTitle?: string;

  messages: ChatMessage[];

  lastMessageAt: string;
  unreadCount: number;
}

export interface ProductReview {
  id: string;
  productId: string;
  buyerId: string;
  buyerName: string;

  rating: number; // 1-5
  comment: string;
  createdAt: string;

  verifiedPurchase?: boolean;
  /** Optional review photo URL (stored in Supabase product-images bucket) */
  imageUrl?: string;
}

// ============================================================
// Translation Types
// ============================================================

export type TranslationKey = string;
export type TranslationDictionary = Record<TranslationKey, string>;
export type LanguageTranslations = Partial<Record<Language, TranslationDictionary>>;
